# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - run: echo ${{ github.event.number }}
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: other/
    - run: ls -lah
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/github-script@v7
      with:
        script: |
          console.log(context);
          console.log("okay");
